# Generated by Django 4.0.6 on 2023-03-18 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bid_sell', '0007_products_latest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
